<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pouexmm" nsURI="http://pouexmm/1.0" nsPrefix="pouexmm">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pouex" lowerBound="1" eType="#//Pouex"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pouex" eSuperTypes="#//LiveObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="defineName cantExistTwoFeatureWithSameName atLeastOneActionForEachFeature"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="defineName" value="not self.name.oclIsUndefined() and self.name &lt;> ''"/>
      <details key="cantExistTwoFeatureWithSameName" value="self.features->isUnique(f: PouexFeature | f.name)"/>
      <details key="atLeastOneActionForEachFeature" value="self.features->forAll(f: PouexFeature | self.actions.influences.feature->exists(inf_feature: PouexFeature | inf_feature = f))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyparts" lowerBound="1"
        upperBound="-1" eType="#//BodyPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="coherentValueMinDefaultMax"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="coherentValueMinDefaultMax" value="self.minimum &lt;= self.default and self.default &lt;= self.maximum"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//InfluenceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Physic" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Emotional" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationConditions" lowerBound="1"
        upperBound="-1" eType="#//ActivationCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivationCondition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="cantModifyFeatureTwiceOrMore"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="cantModifyFeatureTwiceOrMore" value="self.influences->isUnique(i: Influence | i.feature.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="influences" upperBound="-1"
        eType="#//Influence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStatus" eType="#//ActionStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent" eSuperTypes="#//RepeatedAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Influence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//MathematicOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InfluenceType">
    <eLiterals name="POSITIVE"/>
    <eLiterals name="NEGATIVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyPart" eSuperTypes="#//LiveObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subparts" upperBound="-1"
        eType="#//BodyPart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PouexAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" upperBound="-1"
        eType="#//PouexAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//PouexActionFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PouexActionFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinThresholdActivationCondition" eSuperTypes="#//ThresholdActivationCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaxThresholdActivationCondition" eSuperTypes="#//ThresholdActivationCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThresholdActivationCondition" abstract="true"
      eSuperTypes="#//ActivationCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MathematicOperator">
    <eLiterals name="ADDITION"/>
    <eLiterals name="SUBTRACTION" value="1"/>
    <eLiterals name="MULTIPLICATION" value="2"/>
    <eLiterals name="DIVISION" value="3"/>
    <eLiterals name="MODULE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatedAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eachMillisec" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionStatus">
    <eLiterals name="ENABLED"/>
    <eLiterals name="DISABLED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiveObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
